### ISSUE TITLE
Game crashes on startup when certain mods are installed

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Cheaterpaul/fallingleaves#1]
Forge Version: 36.1.3
Minecraft Version: 1.16.5
Falling leaves version: 1.0.0

Example Crash report: https://pastebin.com/PqY0s3pZ
Latest Log: https://pastebin.com/NSnXHx17

Hi,
I've noticed when attempting to use your mod with certain other mods such as Atmospheric or Autumnity, the game just crashes on startup repeatedly, causing me to have to remove the mod so that I can start up the game properly. Atmospheric and Autumnity are just two examples of mods that I've identified that cause this crash. There are definitely more than just these that cause this mod to crash but I've been unable to identify any other particular ones yet. 

I have a feeling it's because these mods add particles to their leaf blocks, similarly to how your mod adds them to vanilla leaves, which may be causing some conflict between these mods.

Let me know if you need any further assistance with this issue and I'd be happy to help whenever I can.

The links to the mods I named can be found below:
Atmospheric: https://www.curseforge.com/minecraft/mc-mods/atmospheric
Autumnity: https://www.curseforge.com/minecraft/mc-mods/autumnity

**Comment by MisakiCopperrose** [comment]
Seem to be having the same issue as well.

Crash report: [crash-2021-03-31_19.14.17-client.txt](https://github.com/Cheaterpaul/fallingleaves/files/6238940/crash-2021-03-31_19.14.17-client.txt)

**Comment by zndrmn** [comment]
I am also Getting the issue. Here is my example.

Crash report: https://gist.github.com/zndrmn/d3c747af92ca9ee111d38fa4e44878f5#file-crash-2021-03-31_20-44-16-client-txt

**Comment by Neko2n** [comment]
I've gotten this crash too. Hoping for a fix soon.

**Comment by The-Bernician-Lamb** [comment]
Hey, Everyone try this latest Alpha version, It appears to fix the issue for me: 
https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge/files/3257607

Does this fix the issue for anyone else?

**Comment by MisakiCopperrose** [comment]
Latest seems to fix it for me, however I am noticing no leaf particles on my dedicated server... It's a bit weird.

**Comment by The-Bernician-Lamb** [comment]
I'm going to close this issue now seeing as everything seems to be working properly. If anyone else still has problems they can open a separate issue.


> Latest seems to fix it for me, however I am noticing no leaf particles on my dedicated server... It's a bit weird.

Hmm that's odd. I'm using my server and I'm not seeing any problems. It's probably a mod conflict or something. I would open a new issue once you've identified a potential mod that's causing it.
