### ISSUE TITLE
[1.18 Forge] Crashes on startup

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Cheaterpaul/fallingleaves#14]
Crashlog:
[https://pastebin.com/nTuHCcy7](https://pastebin.com/nTuHCcy7)

Using mods:

- Optifine
- LazyDFU
- Ding
- Repurposed Structures
- Ferritecore
- Create
- Comforts
- Flywheel
- Geolosys
- Bedspreads
- Iceberg
- MerchantMarkers
- Legendary Tooltips
- Equipment Compare

**Comment by ekiplier** [comment]
The same happened to me on 1.16.5. I think it's something to do with the latest Architectury API update for Forge. Installing architectury-1.26.37 fixed it for me.

[crash-2021-12-11_15.05.39-client.txt](https://github.com/Cheaterpaul/fallingleaves/files/7697262/crash-2021-12-11_15.05.39-client.txt)

**Comment by GeorgeOrwell1** [comment]
For some reason, the mod didn't crash anymore after I updated Forge and Minecraft to 1.18.1 (along with some other mods).
