### ISSUE TITLE
Leaf Type blocks have to end in "_leaves"

### ISSUE THREAD

**Issue by RileyCasper** [Cheaterpaul/fallingleaves#26]
# MCVersion 1.18.2 - FallingLeaves Version 1.3.2
I have a few mods in this mod pack that provide new leaves, but the block id doesn't end in "_leaves", it seems Falling Leaves doesn't register them after I've created a leaf type for them.
![image](https://github.com/Cheaterpaul/fallingleaves/assets/80489042/4fea37a4-3307-4fec-99aa-febc42edac70)
Image is showing block id as "swdm:oak_leaves_variant6"
![image](https://github.com/Cheaterpaul/fallingleaves/assets/80489042/2d795d1a-3693-4492-97f4-0c45f97957dc)
Image of Datapack and file location.

The datapack is indeed working as the other mods that do end in "_leaves" work.
![image](https://github.com/Cheaterpaul/fallingleaves/assets/80489042/2936702a-ebc6-4c6e-89aa-6950b167c91d)
![image](https://github.com/Cheaterpaul/fallingleaves/assets/80489042/aadfb5d7-7573-447f-86b0-74dd157b2c50)
Proof of other Modded blocks are working.

It's just blocks that do not end in _leaves

**Comment by Cheaterpaul** [comment]
you are using the datapack format for falling leaves 2.x.x

You want this https://github.com/Cheaterpaul/fallingleaves/wiki#for-1xx
